### ISSUE TITLE
Magento 2.3 / PHP 7.2: «Property "Title" does not have accessor method "getTitle" in class "Magento\Quote\Api\Data\PaymentInterface"»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [mage2pro/payfort-mageplaza#1]
![01](https://user-images.githubusercontent.com/83204/36014165-a024a0d4-0d92-11e8-9519-a3d06477a15e.png)

**Comment by dmitrii-fediuk** [comment]
Unable to reproduce it.

**Comment by verazia** [comment]
I'm also getting the above error

**Comment by dmitrii-fediuk** [comment]
Banned for double posting.

**Comment by jayantakr1** [comment]
HI @dmitry-fedyuk 
Can you please help me how you have fix this issue ?
