### ISSUE TITLE
«Invalid parameter format»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [mage2pro/payfort-mageplaza#2]
## Request
```
[amount] => 37500
[currency] => SAR
[merchant_identifier] => mbIdehbb
[access_code] => ujIWe0wSHcQoGhevuL8e
[merchant_reference] => ORD-2018/02-01309
[customer_email] => dfediuk@gmail.com
[command] => PURCHASE
[language] => en
[return_url] => https://localhost.com:900/store/payfortfort/payment/response
[signature] => 55101664921ef04a0ad50db543eb4e2d7d9bf96f1973e251af58254a76713f2
```

## Response
```
[amount] => 37500
[response_code] => 00002
[signature] => 4a557f351f0e20ddc3c5b8780d02da43b5da03aebb66d724d0bc0adbb51987f5
[merchant_identifier] => mbIdehbb
[access_code] => ujIWe0wSHcQoGhevuL8e
[customer_ip] => 212.112.100.86
[language] => en
[eci] => ECOMMERCE
[command] => PURCHASE
[response_message] => Invalid parameter format
[merchant_reference] => ORD-2018/02-01309
[customer_email] => dfediuk@gmail.com
[currency] => SAR
[status] => 00
```

**Comment by dmitrii-fediuk** [comment]
The `/` character is not allowed in `merchant_reference`: https://docs.payfort.com/docs/redirection/build/index.html#authorization-purchase-request

**Comment by rahulp-evince** [comment]
Hello Dmitry,

Below are my PayFort request params:

request {
    amount = 90000;
    command = PURCHASE;
    currency = SAR;
    "customer_email" = "john1@mailinator.com";
    "customer_name" = "John1 Doe";
    eci = ECOMMERCE;
    language = en;
    "merchant_reference" = "ABCD-1234";
    "order_description" = "";
    "phone_number" = 852369741;
    "sdk_token" = 884F3B230D5A2431E0530100007FDC9C;
}

Below is the response:
{
    amount = 90000;
    command = PURCHASE;
    currency = SAR;
    "customer_email" = "john1@mailinator.com";
    "customer_name" = "John1 Doe";
    eci = ECOMMERCE;
    language = en;
    "merchant_reference" = "ABCD-1234";
    "phone_number" = 852369741;
    "response_code" = 00002;
    "response_message" = "Invalid parameter format";
    "sdk_token" = 884F3B230D5A2431E0530100007FDC9C;
    status = 00;
}
Can you please let me know what's going wrong from my end for this? I am stuck at this issue and unable to figure out what's wrong getting passed from my side. Any help would be appreciated.

Thanks in advance!

**Comment by dmitrii-fediuk** [comment]
I can fix the «**Invalid parameter format**» error in PayFort for **$200**. 
You can hire me in Upwork for this task: [upwork.com/fl/mage2pro](https://www.upwork.com/fl/mage2pro)
