### ISSUE TITLE
Magento 2.3 / PHP 7.2: «Property "Title" does not have accessor method "getTitle" in class "Magento\Quote\Api\Data\PaymentInterface"

### ISSUE THREAD

**Issue by verazia** [mage2pro/payfort-mageplaza#8]
Magento 2.3 / PHP 7.2: «Property "Title" does not have accessor method "getTitle" in class "Magento\Quote\Api\Data\PaymentInterface"

**Comment by dmitrii-fediuk** [comment]
Banned for double posting.
